INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (959, 'Grilled Chicken Wings', 'Mouth-water chicken wings seasoned in traditional spices and grilled to perfection', 'https://www.recipetineats.com/wp-content/uploads/2014/06/Sticky-Chinese-Chicken-Wings_5.jpg?resize=650,910', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1059, 'Stinky Tofu', 'You will either love it or you will hate it', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Stinkender_Tofu_1.JPG/220px-Stinkender_Tofu_1.JPG', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1959, 'Salad', 'A Goldenwok special', 'https://news.destination-asia.com/wp-content/uploads/2019/01/Jumping-Shrimp-Salad_2_700x459-300x197.jpg', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1399, 'Fried Beef Noodles', 'A Goldenwok classic', 'https://omnivorescookbook.com/wp-content/uploads/2020/06/200430_Beef-Pan-Fried-Noodles_1.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1299, 'General Tsos Chicken on Rice', 'The Chinese staple no Chinese person actually serves at home', 'https://natashaskitchen.com/wp-content/uploads/2020/07/General-Tsos-Chicken-4-500x500.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1899, 'BBQ Pork and Rice', 'Exactly what you would expect it to be', 'https://i0.wp.com/www.themissinglokness.com/wp-content/uploads/2014/04/BJG_7047.jpg?w=850&ssl=1', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (999, 'Red Bean Soup with Glutinous Rice', 'The perfect dessert to leave on the table after dinner', 'https://whattocooktoday.com/wp-content/uploads/2020/12/red-bean-soup-tang-yuan-13.jpg', 3);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (399, 'A slice of orange', 'What happened to the rest of it', 'https://previews.123rf.com/images/pairoj903/pairoj9031507/pairoj903150700073/41771703-orange-slice.jpg', 3);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (399, 'Wong Lo Kat', 'A popular herbal drink known for its eye-catching design which allows it to distinguish itself very clearly amongst other cans in the recycling bin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Wong_Lo_Kat_310mL.JPG/450px-Wong_Lo_Kat_310mL.JPG?20091008044910', 4);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (299, 'Coca Cola', 'A can of coke', 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_1200,h_801/https://lasolas.ca/wp-content/uploads/2020/03/Coca-Cola-can-scaled.jpg', 4);

