INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (959, 'Grilled Chicken Wings', 'Mouth-water chicken wings seasoned in traditional spices and grilled to perfection', 'https://www.recipetineats.com/wp-content/uploads/2014/06/Sticky-Chinese-Chicken-Wings_5.jpg?resize=650,910', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1959, 'Golden Wok Salad', 'A Golden Wok special', 'https://news.destination-asia.com/wp-content/uploads/2019/01/Jumping-Shrimp-Salad_2_700x459-300x197.jpg', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (799, 'Spring Rolls', 'A taste of spring', 'https://www.recipetineats.com/wp-content/uploads/2017/09/Spring-Rolls-4.jpg?w=500&h=375&crop=1', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1059, 'Stinky Tofu', 'People will actually eat this', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Stinkender_Tofu_1.JPG/220px-Stinkender_Tofu_1.JPG', 1);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1399, 'Fried Beef Noodles', 'A Golden Wok classic', 'https://omnivorescookbook.com/wp-content/uploads/2020/06/200430_Beef-Pan-Fried-Noodles_1.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1299, 'General Tsos Chicken on Rice', 'The Chinese staple no Chinese person actually serves at home', 'https://natashaskitchen.com/wp-content/uploads/2020/07/General-Tsos-Chicken-4-500x500.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1599, 'BBQ Pork and Rice', 'Exactly what you would expect it to be', 'https://i0.wp.com/www.themissinglokness.com/wp-content/uploads/2014/04/BJG_7047.jpg?w=850&ssl=1', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1599, 'Roast Pork and Rice', 'Look no further if you need help raising your cholesterol', 'https://christieathome.com/wp-content/uploads/2021/06/Chinese-roasted-pork-belly-32.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1899, 'Roast Duck and Rice', 'Exactly what you would expect it to be', 'https://www.topcitybites.com/wp-content/uploads/gravity_forms/10-c3160174b4dfbf531decf087e428f91d/03/2019/ScreenShot2019-03-06at16.10.15.png', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (1899, 'Sweet and Sour Pork with Rice', 'Exactly what you would expect it to be', 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/aa2dffba333842628649b06c0aad70db/CUT2.jpg', 2);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (999, 'Red Bean Soup with Glutinous Rice', 'The perfect dessert to leave on the table after dinner', 'https://whattocooktoday.com/wp-content/uploads/2020/12/red-bean-soup-tang-yuan-13.jpg', 3);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (999, 'Green Bean Soup', 'For when you want some variety in what to leave on the table after dinner', 'https://souperdiaries.com/wp-content/uploads/2015/09/Green-Bean-Soup-Dessert.jpg', 3);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (299, 'A slice of orange', 'What happened to the rest of it', 'https://previews.123rf.com/images/pairoj903/pairoj9031507/pairoj903150700073/41771703-orange-slice.jpg', 3);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (399, 'Wong Lo Kat', 'A popular herbal drink known for its eye-catching design. Best discarded cold', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Wong_Lo_Kat_310mL.JPG/450px-Wong_Lo_Kat_310mL.JPG?20091008044910', 4);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (299, 'Coca Cola', 'A can of coke', 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_1200,h_801/https://lasolas.ca/wp-content/uploads/2020/03/Coca-Cola-can-scaled.jpg', 4);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (399, 'Coconut Drink', 'Wait, what', 'https://img11.360buyimg.com/imgzone/jfs/t1/83232/13/16989/119891/613c4f52Ef5d9141d/0f0004af8f066e64.jpg', 4);
INSERT INTO menu_items (price, name, description, image_url, category_id) VALUES (299, 'Dr. Thunder', 'Dr. Pepper was fully booked', 'https://64.media.tumblr.com/6b73c5285ae7d37c9cc73c62ed990b2e/8b7834757622254c-f9/s540x810/1722063c54b8ad2250e5f86fe2cf65a8c6b27481.jpg', 4);

